### ISSUE TITLE
Function Invoker calls getWriter() which fails if downstream function calls getOutputStream()

### ISSUE THREAD

**Issue by graemerocher** [GoogleCloudPlatform/functions-framework-java#15]
I have been trying out the function invoker which exhibits an issue if the downstream function calls `getOutputStream`. This is because the framework indiscriminately calls `getWriter()` which is illegal to do in the servlet API if `getOutputStream()` has already been called.

https://github.com/GoogleCloudPlatform/functions-framework-java/blob/5bde734b7155eff7a141b80894244d295dab7fd2/invoker/core/src/main/java/com/google/cloud/functions/invoker/NewHttpFunctionExecutor.java#L76

```
java.lang.IllegalStateException: STREAM
	at org.eclipse.jetty.server.Response.getWriter(Response.java:727)
	at com.google.cloud.functions.invoker.http.HttpResponseImpl.getWriter(HttpResponseImpl.java:94)
	at com.google.cloud.functions.invoker.NewHttpFunctionExecutor.service(NewHttpFunctionExecutor.java:76)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
```

**Comment by graemerocher** [comment]
Note: the problem doesn't manifest when actually deploying the function, only when using the Invoker

**Comment by graemerocher** [comment]
Actually no I am seeing this occur in production as well. I believe `NewHttpFunctionExecutor` should be checking the response as to whether `getOutputStream` or `getWriter` was called and flushing the appropriate instance.

**Comment by eamonnmcmanus** [comment]
Yes, this is clearly a bug. The fix should be straightforward.

**Comment by graemerocher** [comment]
Thanks, when can we expect a new release of the Maven artifacts and for this to be deployed to production? The Micronaut support depends on the fix.
