### ISSUE TITLE
java-function-invoker shaded jackson causes java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by exaV** [GoogleCloudPlatform/functions-framework-java#272]
java-function-invoker incldudes a shaded dependencies and among those is an older version of jackson. This shaded version of jackson uses the same fully qualified classname as the actual jackson package, which causes it to be picked up by the classloader instead of the actual jackson classes.

This breaks my tests after I added a library that uses jackson's JsonFormat.Feature .READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE. When I remove the shaded classes from the test's classpath manually the test works again.

Suggested solution:
This library could just declare a dependency on jackson and instead of shading it into the library jar. If you must use shading you should use the <relocations> feture of the shading plugin to avoid clashing with the real jackson.

Details:
The clash happens when using the following dependencies:
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-test-google-cloud-functions</artifactId>
            <version>3.10.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.langchain4j</groupId>
            <artifactId>quarkus-langchain4j-vertex-ai-gemini</artifactId>
            <version>0.13.1</version>
        </dependency>
```

Full stacktrace:
```
jakarta.ws.rs.ProcessingException: READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE

	at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.unwrap(InvocationBuilderImpl.java:212)
	at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:328)
	at io.quarkiverse.langchain4j.vertexai.runtime.gemini.VertxAiGeminiRestApi$$QuarkusRestClientInterface.predict(Unknown Source)
	at io.quarkiverse.langchain4j.vertexai.runtime.gemini.VertexAiGeminiChatLanguageModel.generate(VertexAiGeminiChatLanguageModel.java:63)
	at dev.langchain4j.model.chat.ChatLanguageModel_I_8A126TctOkbNd3fECMvTFu-JA_Synthetic_ClientProxy.generate(Unknown Source)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:180)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:97)
	at com.github.exav.VertexAiBrainService$$QuarkusImpl.ask(Unknown Source)
	at com.github.exav.VertexAiBrainService$$QuarkusImpl_ClientProxy.ask(Unknown Source)
	at com.github.exav.VertexAiBrainServiceTest.ask_gemini_1000000_tokens(VertexAiBrainServiceTest.kt:18)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1018)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:832)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.NoSuchFieldError: READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.createContextual(EnumDeserializer.java:235)
	at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:851)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:561)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:316)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:265)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:163)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:636)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:190)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:30)
	at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:851)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:561)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:316)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:265)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:163)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:669)
	at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:2450)
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:771)
	at io.quarkus.rest.client.reactive.jackson.runtime.serialisers.ClientJacksonMessageBodyReader.readFrom(ClientJacksonMessageBodyReader.java:52)
	at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.proceed(ClientReaderInterceptorContextImpl.java:86)
	at org.jboss.resteasy.reactive.client.impl.ClientSerialisers.invokeClientReader(ClientSerialisers.java:160)
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.readEntity(RestClientRequestContext.java:209)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.mapToResponse(ClientResponseCompleteRestHandler.java:105)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:35)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseCompleteRestHandler.handle(ClientResponseCompleteRestHandler.java:31)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:231)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
	at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:38)
	at org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:35)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

Helpful links:
- dependency shading: https://github.com/GoogleCloudPlatform/functions-framework-java/blob/main/invoker/core/pom.xml#L176
- relocation documentation: https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html
- jackons docs: https://github.com/FasterXML/jackson-databind/wiki/Deserialization-Features
- JsonFormat.Feature .READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: https://stackoverflow.com/questions/76257484/kafka-json-consumer-error-java-lang-nosuchfielderror-read-unknown-enum-values-u

**Comment by akerekes** [comment]
I've built the library at HEAD and the packaged jackson was 2.15.2 which contains the referenced class: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15#annotations

Closing for now, feel free to reopen if you still experience the issue.
